language: php

php:
  - 5.5
  - 5.6

before_script:
  - git clone -q https://github.com/phalcon/cphalcon.git
  - cd cphalcon/build; sudo ./install
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script: phpunit

matrix:
  allow_failures:
    - php: 5.4
  fast_finish: true

notifications:
    on_success: never
    on_failure: always
